from typing import Any, Iterator


class TimelogError(Exception): ...


class TimelogBusyError(TimelogError): ...


class TimelogIter:
    @property
    def closed(self) -> bool: ...
    def __iter__(self) -> TimelogIter: ...
    def __next__(self) -> tuple[int, object]: ...
    def __len__(self) -> int: ...
    def close(self) -> None: ...


class PageSpan:
    @property
    def closed(self) -> bool: ...
    def __len__(self) -> int: ...
    def close(self) -> None: ...


class PageSpanIter:
    @property
    def closed(self) -> bool: ...
    def __iter__(self) -> PageSpanIter: ...
    def __next__(self) -> PageSpan: ...
    def close(self) -> None: ...


class PageSpanObjectsView:
    @property
    def closed(self) -> bool: ...
    def __iter__(self) -> Iterator[object]: ...


class Timelog:
    @property
    def closed(self) -> bool: ...
    @property
    def busy_events(self) -> int: ...
    @property
    def time_unit(self) -> str: ...
    @property
    def maintenance_mode(self) -> str: ...
    @property
    def busy_policy(self) -> str: ...

    def __init__(self, **kwargs: Any) -> None: ...
    def append(self, *args: Any, **kwargs: Any) -> None: ...
    def extend(self, iterable: Any, *, mostly_ordered: bool = ...) -> None: ...
    def bulk_append(
        self,
        timestamps: Any,
        objects: Any,
        *,
        mostly_ordered: bool | None = ...,
    ) -> None: ...
    def delete_before(self, ts: int) -> None: ...
    def delete_range(self, t1: int, t2: int) -> None: ...
    def stats(self) -> dict[str, Any]: ...
    def all(self) -> TimelogIter: ...
    def point(self, ts: int) -> TimelogIter: ...
    def equal(self, ts: int) -> TimelogIter: ...
    def range(self, t1: int, t2: int) -> TimelogIter: ...
    def since(self, ts: int) -> TimelogIter: ...
    def until(self, ts: int) -> TimelogIter: ...
    def page_spans(self, t1: int, t2: int, *, kind: str = ...) -> PageSpanIter: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def compact(self) -> None: ...
    def maint_step(self) -> None: ...
    def _set_min_ts_floor(self, min_ts: int | None) -> None: ...
    def _min_ts_floor(self) -> int | None: ...
