from types import TracebackType
from typing import Any, Iterator


class TimelogError(Exception): ...


class TimelogBusyError(TimelogError): ...


class TimelogIter:
    @property
    def closed(self) -> bool: ...
    def __iter__(self) -> TimelogIter: ...
    def __next__(self) -> tuple[int, object]: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> TimelogIter: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool: ...
    def close(self) -> None: ...
    def next_batch(self, n: int) -> list[tuple[int, object]]: ...
    def view(self) -> PageSpanIter: ...


class PageSpan:
    @property
    def closed(self) -> bool: ...
    @property
    def timestamps(self) -> memoryview: ...
    @property
    def start_ts(self) -> int: ...
    @property
    def end_ts(self) -> int: ...
    @property
    def last_ts(self) -> int: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> PageSpan: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool: ...
    def close(self) -> None: ...
    def objects(self) -> PageSpanObjectsView: ...
    def copy_timestamps(self) -> list[int]: ...


class PageSpanIter:
    @property
    def closed(self) -> bool: ...
    def __iter__(self) -> PageSpanIter: ...
    def __next__(self) -> PageSpan: ...
    def __enter__(self) -> PageSpanIter: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool: ...
    def close(self) -> None: ...


class PageSpanObjectsView:
    @property
    def closed(self) -> bool: ...
    def __iter__(self) -> Iterator[object]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> object: ...
    def copy(self) -> list[object]: ...


class Timelog:
    @property
    def closed(self) -> bool: ...
    @property
    def busy_events(self) -> int: ...
    @property
    def time_unit(self) -> str: ...
    @property
    def maintenance_mode(self) -> str: ...
    @property
    def busy_policy(self) -> str: ...
    @property
    def retired_queue_len(self) -> int: ...
    @property
    def alloc_failures(self) -> int: ...

    def __init__(self, **kwargs: Any) -> None: ...
    def append(self, *args: Any, **kwargs: Any) -> None: ...
    def extend(self, iterable: Any, *, mostly_ordered: bool = ...) -> None: ...
    def bulk_append(
        self,
        timestamps: Any,
        objects: Any,
        *,
        mostly_ordered: bool | None = ...,
    ) -> None: ...
    def delete_before(self, ts: int) -> None: ...
    def delete_range(self, t1: int, t2: int) -> None: ...
    def stats(self) -> dict[str, Any]: ...
    def start_maintenance(self) -> None: ...
    def stop_maintenance(self) -> None: ...
    def all(self) -> TimelogIter: ...
    def point(self, ts: int) -> TimelogIter: ...
    def equal(self, ts: int) -> TimelogIter: ...
    def range(self, t1: int, t2: int) -> TimelogIter: ...
    def since(self, ts: int) -> TimelogIter: ...
    def until(self, ts: int) -> TimelogIter: ...
    def min_ts(self) -> int | None: ...
    def max_ts(self) -> int | None: ...
    def next_ts(self, ts: int) -> int | None: ...
    def prev_ts(self, ts: int) -> int | None: ...
    def validate(self) -> None: ...
    def page_spans(self, t1: int, t2: int, *, kind: str = ...) -> PageSpanIter: ...
    def views(self, t1: int, t2: int, *, kind: str = ...) -> PageSpanIter: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def compact(self) -> None: ...
    def maint_step(self) -> bool: ...
    def __enter__(self) -> Timelog: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool: ...
    def _set_min_ts_floor(self, min_ts: int | None) -> None: ...
    def _min_ts_floor(self) -> int | None: ...
