# CMake generated Testfile for 
# Source directory: U:/Projects/timelog/bindings/cpython
# Build directory: U:/Projects/timelog/bindings/cpython/build-test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(py_handle_tests "U:/Projects/timelog/bindings/cpython/build-test/Debug/test_py_handle.exe")
  set_tests_properties(py_handle_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;496;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(py_handle_tests "U:/Projects/timelog/bindings/cpython/build-test/Release/test_py_handle.exe")
  set_tests_properties(py_handle_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;496;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(py_handle_tests "U:/Projects/timelog/bindings/cpython/build-test/MinSizeRel/test_py_handle.exe")
  set_tests_properties(py_handle_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;496;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(py_handle_tests "U:/Projects/timelog/bindings/cpython/build-test/RelWithDebInfo/test_py_handle.exe")
  set_tests_properties(py_handle_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;496;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
else()
  add_test(py_handle_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(py_timelog_tests "U:/Projects/timelog/bindings/cpython/build-test/Debug/test_py_timelog.exe")
  set_tests_properties(py_timelog_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;501;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(py_timelog_tests "U:/Projects/timelog/bindings/cpython/build-test/Release/test_py_timelog.exe")
  set_tests_properties(py_timelog_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;501;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(py_timelog_tests "U:/Projects/timelog/bindings/cpython/build-test/MinSizeRel/test_py_timelog.exe")
  set_tests_properties(py_timelog_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;501;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(py_timelog_tests "U:/Projects/timelog/bindings/cpython/build-test/RelWithDebInfo/test_py_timelog.exe")
  set_tests_properties(py_timelog_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;501;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
else()
  add_test(py_timelog_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(py_iter_tests "U:/Projects/timelog/bindings/cpython/build-test/Debug/test_py_iter.exe")
  set_tests_properties(py_iter_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;506;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(py_iter_tests "U:/Projects/timelog/bindings/cpython/build-test/Release/test_py_iter.exe")
  set_tests_properties(py_iter_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;506;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(py_iter_tests "U:/Projects/timelog/bindings/cpython/build-test/MinSizeRel/test_py_iter.exe")
  set_tests_properties(py_iter_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;506;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(py_iter_tests "U:/Projects/timelog/bindings/cpython/build-test/RelWithDebInfo/test_py_iter.exe")
  set_tests_properties(py_iter_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;506;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
else()
  add_test(py_iter_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(py_span_tests "U:/Projects/timelog/bindings/cpython/build-test/Debug/test_py_span.exe")
  set_tests_properties(py_span_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;511;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(py_span_tests "U:/Projects/timelog/bindings/cpython/build-test/Release/test_py_span.exe")
  set_tests_properties(py_span_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;511;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(py_span_tests "U:/Projects/timelog/bindings/cpython/build-test/MinSizeRel/test_py_span.exe")
  set_tests_properties(py_span_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;511;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(py_span_tests "U:/Projects/timelog/bindings/cpython/build-test/RelWithDebInfo/test_py_span.exe")
  set_tests_properties(py_span_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;511;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
else()
  add_test(py_span_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(py_maint_b5_tests "U:/Projects/timelog/bindings/cpython/build-test/Debug/test_py_maint_b5.exe")
  set_tests_properties(py_maint_b5_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;516;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(py_maint_b5_tests "U:/Projects/timelog/bindings/cpython/build-test/Release/test_py_maint_b5.exe")
  set_tests_properties(py_maint_b5_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;516;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(py_maint_b5_tests "U:/Projects/timelog/bindings/cpython/build-test/MinSizeRel/test_py_maint_b5.exe")
  set_tests_properties(py_maint_b5_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;516;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(py_maint_b5_tests "U:/Projects/timelog/bindings/cpython/build-test/RelWithDebInfo/test_py_maint_b5.exe")
  set_tests_properties(py_maint_b5_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;516;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
else()
  add_test(py_maint_b5_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(py_errors_tests "U:/Projects/timelog/bindings/cpython/build-test/Debug/test_py_errors.exe")
  set_tests_properties(py_errors_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;521;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(py_errors_tests "U:/Projects/timelog/bindings/cpython/build-test/Release/test_py_errors.exe")
  set_tests_properties(py_errors_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;521;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(py_errors_tests "U:/Projects/timelog/bindings/cpython/build-test/MinSizeRel/test_py_errors.exe")
  set_tests_properties(py_errors_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;521;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(py_errors_tests "U:/Projects/timelog/bindings/cpython/build-test/RelWithDebInfo/test_py_errors.exe")
  set_tests_properties(py_errors_tests PROPERTIES  WORKING_DIRECTORY "U:/Projects/timelog/bindings/cpython/build-test" _BACKTRACE_TRIPLES "U:/Projects/timelog/bindings/cpython/CMakeLists.txt;521;add_test;U:/Projects/timelog/bindings/cpython/CMakeLists.txt;0;")
else()
  add_test(py_errors_tests NOT_AVAILABLE)
endif()
